import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wallet Pass',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
